### ISSUE TITLE
SSL Replication not using the percona data bag

### ISSUE THREAD

**Issue by devsibwarra** [sous-chefs/chef-percona#358]
Using chef-percona 0.16.1, I attempted to setup Percona replication with SSL support with these settings

``` json
# nodes/server.json
        "run_list": [
                "recipe[percona::client]",
                "recipe[percona::server]",
                "recipe[percona::replication]"
        ],
        "percona": {
                "encrypted_data_bag": "dev_mysql",
                "encrypted_data_bag_secret_file": "/etc/chef/dev_databag_secret",
                "server": {
                        "replication": {
                                "ssl_enabled": true,
                                "host": "1.2.3.4"
                        },
                        "role": [ "master", "slave" ]
                }
        },
```

The Chef run failed with the following error

```
ArgumentError
-------------
No secret specified and no secret found at /etc/chef/encrypted_data_bag_secret

Cookbook Trace:
---------------
  /var/chef/cookbooks/percona/recipes/ssl.rb:15:in `from_file'
  /var/chef/cookbooks/percona/recipes/configure_server.rb:118:in `from_file'
  /var/chef/cookbooks/percona/recipes/server.rb:38:in `from_file'

Relevant File Content:
----------------------
/var/chef/cookbooks/percona/recipes/ssl.rb:

  8:  data_bag = node["percona"]["encrypted_data_bag"]
  9:
 10:  directory certs_path do
 11:    owner node["percona"]["server"]["username"]
 12:    mode "0700"
 13:  end
 14:
 15>> certs = Chef::EncryptedDataBagItem.load(
 16:    data_bag,
 17:    node["percona"]["encrypted_data_bag_item_ssl_replication"]
 18:  )
 19:
 20:  # place the CA certificate, it should be present on both master and slave
 21:  file "#{certs_path}/cacert.pem" do
 22:    content certs["ca-cert"]
 23:    sensitive true
 24:  end
```

**Comment by shortdudey123** [comment]
@devsibwarra that error means you don't have a secret or you don't have it in the standard place

**Comment by devsibwarra** [comment]
@shortdudey123 Yes, that's the point.  Our development environment databag is stored in an alternate location.  The other databag uses in the percona cookbook use `node["percona"]["encrypted_data_bag_secret_file"]`, so I didn't see a reason why the SSL recipe would be excluded
